# Generated by Django 5.2.1 on 2025-06-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Qarz miqdori"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="To'lov Miqdori",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Oylik", "Oylik"),
                    ("Premium", "Premium"),
                    ("Kunlik", "Kunlik"),
                ],
                default="Oylik",
                max_length=50,
                verbose_name="To'lov turi",
            ),
        ),
    ]
