# Generated by Django 5.1.3 on 2025-07-05 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancereport",
            options={
                "ordering": ["-date", "-check_in_time"],
                "verbose_name": "Attendance Report",
                "verbose_name_plural": "Attendance Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="incomeexpensereport",
            options={
                "ordering": ["-date"],
                "verbose_name": "Income Expense Report",
                "verbose_name_plural": "Income Expense Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="membershipsale",
            options={
                "ordering": ["-sale_date"],
                "verbose_name": "Membership Sale",
                "verbose_name_plural": "Membership Sales",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-end_date"],
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Check-in Time"),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="check_out_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Check-out Time"
            ),
        ),
        migrations.AddField(
            model_name="attendancereport",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Duration (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="incomeexpensereport",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="membershipsale",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="membershipsale",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Oylik", "Oylik"),
                    ("Premium", "Premium"),
                    ("Kunlik", "Kunlik"),
                ],
                default="Oylik",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("Oylik", "Oylik"),
                    ("Premium", "Premium"),
                    ("Kunlik", "Kunlik"),
                ],
                default="Oylik",
                max_length=20,
                verbose_name="Subscription Type",
            ),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="branch",
            field=models.CharField(max_length=100, verbose_name="Branch"),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Report Date"
            ),
        ),
        migrations.AlterField(
            model_name="attendancereport",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_reports",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="incomeexpensereport",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Report Date"
            ),
        ),
        migrations.AlterField(
            model_name="incomeexpensereport",
            name="expenses",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Total Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="incomeexpensereport",
            name="income",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Total Income"
            ),
        ),
        migrations.AlterField(
            model_name="membershipsale",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Sale Amount"
            ),
        ),
        migrations.AlterField(
            model_name="membershipsale",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_sales",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="membershipsale",
            name="sale_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Sale Date"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterUniqueTogether(
            name="attendancereport",
            unique_together={("member", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="incomeexpensereport",
            unique_together={("date",)},
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(fields=["date"], name="reports_att_date_44a0a5_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(
                fields=["member", "date"], name="reports_att_member__3c8fbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancereport",
            index=models.Index(
                fields=["branch", "date"], name="reports_att_branch_29e7be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incomeexpensereport",
            index=models.Index(fields=["date"], name="reports_inc_date_64b888_idx"),
        ),
        migrations.AddIndex(
            model_name="membershipsale",
            index=models.Index(
                fields=["sale_date"], name="reports_mem_sale_da_ca1738_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipsale",
            index=models.Index(
                fields=["member", "sale_date"], name="reports_mem_member__68820d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["start_date", "end_date"], name="reports_sub_start_d_01e85e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["member", "is_active"], name="reports_sub_member__113cd8_idx"
            ),
        ),
    ]
