# Generated by Django 5.1.3 on 2025-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_attendancereport_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("income", models.FloatField(default=0)),
                ("expense", models.FloatField(default=0)),
                ("new_members", models.PositiveIntegerField(default=0)),
                ("renewals", models.PositiveIntegerField(default=0)),
                ("total_members", models.PositiveIntegerField(default=0)),
                ("check_ins", models.PositiveIntegerField(default=0)),
                ("expiring_soon", models.PositiveIntegerField(default=0)),
                ("active_members", models.PositiveIntegerField(default=0)),
                ("male_members", models.PositiveIntegerField(default=0)),
                ("female_members", models.PositiveIntegerField(default=0)),
                ("cash_income", models.FloatField(default=0)),
                ("card_income", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Daily Report",
                "verbose_name_plural": "Daily Reports",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(db_index=True, unique=True)),
                ("income", models.FloatField(default=0)),
                ("expense", models.FloatField(default=0)),
                ("new_members", models.PositiveIntegerField(default=0)),
                ("renewals", models.PositiveIntegerField(default=0)),
                ("total_members", models.PositiveIntegerField(default=0)),
                ("check_ins", models.PositiveIntegerField(default=0)),
                ("expiring_soon", models.PositiveIntegerField(default=0)),
                ("active_members", models.PositiveIntegerField(default=0)),
                ("male_members", models.PositiveIntegerField(default=0)),
                ("female_members", models.PositiveIntegerField(default=0)),
                ("cash_income", models.FloatField(default=0)),
                ("card_income", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Monthly Report",
                "verbose_name_plural": "Monthly Reports",
                "ordering": ["-month"],
            },
        ),
    ]
