# Generated by Django 5.1.3 on 2025-07-25 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_dailyreport_monthlyreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancereport",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Report Date"
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="incomeexpensereport",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Report Date"
            ),
        ),
        migrations.AlterField(
            model_name="membershipsale",
            name="sale_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Sale Date"
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="month",
            field=models.DateTimeField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(verbose_name="Start Date"),
        ),
    ]
