# Generated by Django 5.2 on 2025-06-02 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nomi")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fitness_club_logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "daily",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Kunlik"
                    ),
                ),
                (
                    "monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Oylik"
                    ),
                ),
                ("vip", models.BooleanField(default=False, verbose_name="VIP")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state", models.BooleanField(default=True)),
                ("f_name", models.CharField(max_length=255, verbose_name="Ism")),
                ("l_name", models.CharField(max_length=255, verbose_name="Familiya")),
                (
                    "phone",
                    models.CharField(
                        help_text="Telefon raqamingizni kiriting (masalan: +998...)",
                        max_length=20,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("E", "Erkak"), ("A", "Ayol")],
                        max_length=1,
                        verbose_name="Jins",
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        help_text="PIN kodni kiriting (4 raqamli)",
                        max_length=4,
                        unique=True,
                        verbose_name="PIN kod",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=50, verbose_name="Tolov miqdori"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("Oylik", "Oylik"),
                            ("Premium", "Premium"),
                            ("Kunlik", "Kunlik"),
                        ],
                        default="Oylik",
                        max_length=50,
                    ),
                ),
                ("branch", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendedTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state", models.BooleanField(default=True)),
                ("attended_at", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attended_times",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "attended_at")},
            },
        ),
    ]
