# Generated by Django 5.1.3 on 2025-07-15 05:12

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendedtime",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="attendedtime",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="attendedtime",
            name="member",
        ),
        migrations.RemoveField(
            model_name="attendedtime",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="fitnessclub",
            options={"verbose_name_plural": "Fitness klublar"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name_plural": "Aʼzolar"},
        ),
        migrations.RemoveField(
            model_name="member",
            name="branch",
        ),
        migrations.AlterField(
            model_name="fitnessclub",
            name="daily",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Kunlik narx"
            ),
        ),
        migrations.AlterField(
            model_name="fitnessclub",
            name="monthly",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Oylik narx"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="To‘lov miqdori"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Kunlik", "Kunlik"),
                    ("Oylik", "Oylik"),
                    ("Premium", "Premium"),
                ],
                default="Oylik",
                max_length=8,
                verbose_name="To‘lov turi",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="member",
            name="pin_code",
            field=models.CharField(
                max_length=4,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{4}$", "PIN kod faqat 4 ta raqamdan iborat bo‘lishi kerak."
                    )
                ],
                verbose_name="PIN kod",
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["phone"], name="members_mem_phone_94f004_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["pin_code"], name="members_mem_pin_cod_c2568f_idx"
            ),
        ),
        migrations.DeleteModel(
            name="AttendedTime",
        ),
    ]
