# Generated by Django 5.1.3 on 2025-07-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_attendedtime_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessclub",
            name="daily",
            field=models.FloatField(verbose_name="Kunlik narx"),
        ),
        migrations.AlterField(
            model_name="fitnessclub",
            name="monthly",
            field=models.FloatField(verbose_name="Oylik narx"),
        ),
        migrations.AlterField(
            model_name="member",
            name="payment_amount",
            field=models.FloatField(verbose_name="To‘lov miqdori"),
        ),
    ]
