# Generated by Django 5.2.1 on 2025-07-02 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_options_and_more"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_attendance_member_per_day",
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", True)),
                fields=("member",),
                include=("attended_at",),
                name="unique_attendance_member_per_day",
                violation_error_message="A member can only check in once per day.",
            ),
        ),
    ]
