# Generated by Django 5.1.3 on 2025-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0003_remove_attendance_unique_attendance_member_per_day_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attended_at",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
