# Generated by Django 5.1.3 on 2025-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendance_attended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attended_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
